services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: promptrepo-backend-dev
    ports:
      - "8080:8080"
      - "5678:5678"  # Debug port
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/.venv
      - ./database:/database
      - ./repos:/repos
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    networks:
      - promptrepo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: promptrepo-frontend-dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debug port
    environment:
      - BACKEND_URL=http://backend:8080
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    networks:
      - promptrepo-network

networks:
  promptrepo-network:
    driver: bridge