[project]
name = "promptrepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "python-dotenv==1.1.1",
    "reflex==0.8.4",
]
