version: '3'

tasks:
  up:
    desc: "Build and run development containers in detached mode"
    cmds:
      - docker-compose -f docker-compose.dev.yml up --build -d
      - echo "Development containers started"
      - docker-compose -f docker-compose.dev.yml logs -f

  logs:
    desc: "Show development container logs"
    cmds:
      - docker-compose -f docker-compose.dev.yml logs -f

  down:
    desc: "Stop development containers"
    cmds:
      - docker-compose -f docker-compose.dev.yml down

  down-volumes:
    desc: "Stop development containers and remove volumes"
    cmds:
      - docker-compose -f docker-compose.dev.yml down -v

  down-hard:
    desc: "Stop containers, remove volumes, and clean database/repos folders"
    cmds:
      - task: down-volumes
      - rm -rf backend/database
      - rm -rf backend/repos
      - rm -rf database
      - rm -rf repos
      - echo "Hard cleanup completed - removed database and repos folders"

  rebuild:
    desc: "Rebuild and restart development containers"
    cmds:
      - docker-compose -f docker-compose.dev.yml down
      - docker-compose -f docker-compose.dev.yml up --build -d

  backend-logs:
    desc: "Show logs for backend service only"
    cmds:
      - docker-compose -f docker-compose.dev.yml logs -f backend

  frontend-logs:
    desc: "Show logs for frontend service only"
    cmds:
      - docker-compose -f docker-compose.dev.yml logs -f frontend