import { Prompt } from '../_state/promptState';

export const mockPrompts: Prompt[] = [
  {
    id: 'prompt_1',
    name: 'Code Review Assistant',
    description: 'Helps review code for best practices, bugs, and improvements',
    prompt: 'You are an experienced code reviewer. Analyze the following code and provide feedback on:\n\n1. Code quality and best practices\n2. Potential bugs or security issues\n3. Performance optimizations\n4. Code readability and maintainability\n5. Suggestions for improvement\n\nCode to review:\n\n{code}',
    model: 'openai/gpt-4',
    failover_model: 'anthropic/claude-3-sonnet',
    temperature: 0.3,
    top_p: 0.9,
    max_tokens: 2048,
    thinking_enabled: true,
    thinking_budget: 15000,
    created_at: new Date('2024-01-15T10:30:00Z'),
    updated_at: new Date('2024-01-20T14:22:00Z'),
  },
  {
    id: 'prompt_2',
    name: 'Technical Documentation Writer',
    description: 'Creates comprehensive technical documentation from code and requirements',
    prompt: 'You are a technical documentation expert. Create clear, comprehensive documentation for the following:\n\n**Task**: {task_type}\n**Context**: {context}\n**Requirements**: {requirements}\n\nInclude:\n- Overview and purpose\n- Prerequisites\n- Step-by-step instructions\n- Code examples\n- Troubleshooting section\n- Best practices\n\nWrite in markdown format.',
    model: 'anthropic/claude-3-sonnet',
    failover_model: 'openai/gpt-4',
    temperature: 0.4,
    top_p: 0.95,
    max_tokens: 4096,
    thinking_enabled: false,
    thinking_budget: 10000,
    created_at: new Date('2024-01-10T09:15:00Z'),
    updated_at: new Date('2024-01-25T16:45:00Z'),
  },
  {
    id: 'prompt_3',
    name: 'API Design Consultant',
    description: 'Designs RESTful APIs following best practices and industry standards',
    prompt: 'You are an API design expert. Design a RESTful API for the following requirements:\n\n**Domain**: {domain}\n**Entities**: {entities}\n**Operations**: {operations}\n**Constraints**: {constraints}\n\nProvide:\n1. Resource endpoints with HTTP methods\n2. Request/response schemas\n3. Error handling strategy\n4. Authentication requirements\n5. Rate limiting considerations\n6. Versioning strategy\n7. OpenAPI specification\n\nFollow REST principles and industry best practices.',
    model: 'openai/gpt-4-turbo',
    failover_model: 'anthropic/claude-3-opus',
    temperature: 0.5,
    top_p: 0.9,
    max_tokens: 3072,
    thinking_enabled: true,
    thinking_budget: 20000,
    created_at: new Date('2024-01-08T13:20:00Z'),
    updated_at: new Date('2024-01-22T11:30:00Z'),
  },
  {
    id: 'prompt_4',
    name: 'SQL Query Optimizer',
    description: 'Analyzes and optimizes SQL queries for better performance',
    prompt: 'You are a database optimization expert. Analyze the following SQL query and provide optimization suggestions:\n\n**Query**: \n```sql\n{query}\n```\n\n**Schema Info**: {schema}\n**Performance Issues**: {issues}\n\nProvide:\n1. Query analysis\n2. Performance bottlenecks\n3. Optimized query version\n4. Index recommendations\n5. Explanation of improvements\n6. Alternative approaches if applicable\n\nFocus on query execution plans and database-specific optimizations.',
    model: 'anthropic/claude-3-haiku',
    failover_model: 'openai/gpt-3.5-turbo',
    temperature: 0.2,
    top_p: 0.8,
    max_tokens: 1536,
    thinking_enabled: false,
    thinking_budget: 8000,
    created_at: new Date('2024-01-12T15:45:00Z'),
    updated_at: new Date('2024-01-18T09:12:00Z'),
  },
  {
    id: 'prompt_5',
    name: 'System Architecture Advisor',
    description: 'Provides guidance on system architecture and design patterns',
    prompt: 'You are a senior software architect. Design a system architecture for:\n\n**Requirements**:\n- Functionality: {functionality}\n- Scale: {scale}\n- Performance: {performance_requirements}\n- Constraints: {constraints}\n- Technology Stack: {tech_stack}\n\n**Deliverables**:\n1. High-level architecture diagram (describe in text)\n2. Component breakdown\n3. Data flow description\n4. Technology recommendations\n5. Scalability considerations\n6. Security measures\n7. Deployment strategy\n8. Monitoring and observability\n\nConsider microservices, event-driven patterns, and cloud-native approaches.',
    model: 'openai/gpt-4',
    failover_model: 'anthropic/claude-3-sonnet',
    temperature: 0.6,
    top_p: 0.95,
    max_tokens: 4096,
    thinking_enabled: true,
    thinking_budget: 25000,
    created_at: new Date('2024-01-05T11:00:00Z'),
    updated_at: new Date('2024-01-28T13:18:00Z'),
  },
  {
    id: 'prompt_6',
    name: 'Bug Diagnosis Expert',
    description: 'Helps diagnose and troubleshoot software bugs and issues',
    prompt: 'You are a debugging expert. Help diagnose the following issue:\n\n**Problem Description**: {problem}\n**Error Messages**: {errors}\n**Environment**: {environment}\n**Steps to Reproduce**: {steps}\n**Expected Behavior**: {expected}\n**Actual Behavior**: {actual}\n\n**Analysis needed**:\n1. Root cause analysis\n2. Possible causes ranked by likelihood\n3. Debugging steps to isolate the issue\n4. Recommended fixes\n5. Prevention strategies\n6. Related issues to check\n\nProvide systematic approach to debugging.',
    model: 'anthropic/claude-3-sonnet',
    failover_model: 'openai/gpt-4',
    temperature: 0.3,
    top_p: 0.9,
    max_tokens: 2048,
    thinking_enabled: true,
    thinking_budget: 18000,
    created_at: new Date('2024-01-14T08:30:00Z'),
    updated_at: new Date('2024-01-21T17:25:00Z'),
  },
  {
    id: 'prompt_7',
    name: 'Security Assessment Specialist',
    description: 'Conducts security reviews and vulnerability assessments',
    prompt: 'You are a cybersecurity expert. Conduct a security assessment for:\n\n**Target**: {target_system}\n**Architecture**: {architecture}\n**Technologies**: {technologies}\n**Access Patterns**: {access_patterns}\n**Data Sensitivity**: {data_sensitivity}\n\n**Assessment Areas**:\n1. Authentication and authorization\n2. Data protection and encryption\n3. Input validation and sanitization\n4. API security\n5. Infrastructure security\n6. Code security\n7. Compliance requirements\n\n**Deliverables**:\n- Vulnerability assessment\n- Risk prioritization\n- Remediation recommendations\n- Security best practices\n- Compliance checklist',
    model: 'openai/gpt-4-turbo',
    failover_model: 'anthropic/claude-3-opus',
    temperature: 0.4,
    top_p: 0.9,
    max_tokens: 3072,
    thinking_enabled: false,
    thinking_budget: 12000,
    created_at: new Date('2024-01-09T14:15:00Z'),
    updated_at: new Date('2024-01-26T10:42:00Z'),
  },
  {
    id: 'prompt_8',
    name: 'Performance Tuning Guide',
    description: 'Optimizes application performance across different layers',
    prompt: 'You are a performance optimization expert. Analyze and optimize performance for:\n\n**Application Type**: {app_type}\n**Current Metrics**: {current_metrics}\n**Performance Goals**: {goals}\n**Bottlenecks**: {bottlenecks}\n**Environment**: {environment}\n\n**Analysis Areas**:\n1. Frontend performance (if applicable)\n2. Backend optimization\n3. Database performance\n4. Network optimization\n5. Caching strategies\n6. Resource utilization\n\n**Provide**:\n- Performance analysis\n- Optimization recommendations\n- Implementation priority\n- Expected improvements\n- Monitoring setup\n- Load testing strategy',
    model: 'anthropic/claude-3-haiku',
    failover_model: 'openai/gpt-3.5-turbo',
    temperature: 0.5,
    top_p: 0.9,
    max_tokens: 2560,
    thinking_enabled: true,
    thinking_budget: 16000,
    created_at: new Date('2024-01-11T12:00:00Z'),
    updated_at: new Date('2024-01-24T15:33:00Z'),
  },
];

export const getModelOptions = () => {
  return [
    { value: 'openai/gpt-4', label: 'GPT-4 (OpenAI)' },
    { value: 'openai/gpt-4-turbo', label: 'GPT-4 Turbo (OpenAI)' },
    { value: 'openai/gpt-3.5-turbo', label: 'GPT-3.5 Turbo (OpenAI)' },
    { value: 'anthropic/claude-3-opus', label: 'Claude 3 Opus (Anthropic)' },
    { value: 'anthropic/claude-3-sonnet', label: 'Claude 3 Sonnet (Anthropic)' },
    { value: 'anthropic/claude-3-haiku', label: 'Claude 3 Haiku (Anthropic)' },
  ];
};